export const CALCULATE_MORTGAGE = 'CALCULATE_MORTGAGE';

// Extra Payments actions
export const ADD_EXTRA_PAYMENT = 'ADD_EXTRA_PAYMENT';
export const REMOVE_EXTRA_PAYMENT = 'REMOVE_EXTRA_PAYMENT';
export const EDIT_EXTRA_PAYMENT = 'EDIT_EXTRA_PAYMENT';
