export const CALCULATE_MORTGAGE = 'CALCULATE_MORTGAGE';

// Extra Payments actions
export const ADD_EXTRA_PAYMENT = 'ADD_EXTRA_PAYMENT';
export const REMOVE_EXTRA_PAYMENT = 'REMOVE_EXTRA_PAYMENT';
export const EDIT_EXTRA_PAYMENT = 'EDIT_EXTRA_PAYMENT';
export const SAVE_EXTRA_PAYMENT = 'SAVE_EXTRA_PAYMENT';
export const CANCEL_EXTRA_PAYMENT_EDIT = 'CANCEL_EXTRA_PAYMENT_EDIT';
